version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - docker.env
    environment:
    - POSTGRES_HOST=localhost
    - POSTGRES_PORT=5432
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=nestjs
    networks:
    - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "5050:5050"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    environment:
    - PGADMIN_EMAIL=admin@mail.com
    - PGADMIN_PASSWORD=admin
    - PGADMIN_LISTEN_PORT=5050
    networks:
    - postgres
 
networks:
  postgres:
    driver: bridge